<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.csproj.xml" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <PackageId>Camille.Core</PackageId>
    <RootNamespace>Camille.Core</RootNamespace>
    <Description>Core utilities for Camille packages.</Description>
      <NoWarn>1701;1702;NU1903;CS0612</NoWarn>
  </PropertyGroup>
</Project>
